---

- name: add cord chart repo
  kubernetes.core.helm_repository:
    name: cord
    repo_url: "https://charts.opencord.org"
  when: inventory_hostname in groups['master_nodes']

- name: add aether chart repo
  kubernetes.core.helm_repository:
    name: aether
    repo_url: "https://charts.aetherproject.org"
  when: inventory_hostname in groups['master_nodes']

- name: find {{ core.data_iface }}'s subnet for RAN
  shell: ip route | grep {{ core.data_iface }} | awk '/kernel/ {print $1}' | head -1
  register: result
  when: inventory_hostname in groups['master_nodes']
  become: true

# TODO: check if interface subnet is valid
- set_fact:
    ran_subnet: "{{ result.stdout if (aether.ran_subnet == '') else aether.ran_subnet }}"
  when: inventory_hostname in groups['master_nodes']

- debug:
    var: "ran_subnet"

- name: remove /tmp/sdcore-4g-values.yaml
  file:
    path: "/tmp/sdcore-4g-values.yaml"
    state: absent
  when: inventory_hostname in groups['master_nodes']

- name: copy {{ ROOT_DIR }}/{{ core.values_file }} to /tmp/sdcore-4g-values.yaml
  template:
    src: "{{ ROOT_DIR }}/{{ core.values_file }}"
    dest: "/tmp/sdcore-4g-values.yaml"
  when: inventory_hostname in groups['master_nodes']

# - name: update aether 5gc helm dependencies
#   shell: |
#     helm dep up "{{ core.helm.chart_ref }}"
#   when: inventory_hostname in groups['master_nodes']

# TODO: add systems check to avoid issues (e.g., mongodb needing avx support)
- name: deploy aether 4gc
  block:
    - name: deploy aether 4gc
      kubernetes.core.helm:
        update_repo_cache: true
        name: sd-core
        release_namespace: omec
        create_namespace: true
        chart_ref: "{{ core.helm.chart_ref }}"
        chart_version: "{{ core.helm.chart_version }}"
        values_files:
          - /tmp/sdcore-4g-values.yaml
        wait: true
        wait_timeout: "1m30s"
        force: true
      when: inventory_hostname in groups['master_nodes']

  rescue:
    - name: Get Pods Status
      shell: kubectl get po -n omec
      register: pod_status
      changed_when: false
      when: inventory_hostname in groups['master_nodes']

    - name: restart Pods if not running
      shell: |
        while IFS= read -r line; do
          name=$(echo "$line" | awk '{print $1}')
          status=$(echo "$line" | awk '{print $3}')

          if [[ "$status" != "Running" ]]; then
            kubectl delete pod "$name" -n omec
          fi
        done <<< "{{ pod_status.stdout }}"
      args:
        executable: /bin/bash
      when: inventory_hostname in groups['master_nodes']
  always:
    - pause:
        seconds: 180
